spring:
  application:
    name: cricket-analytics

  datasource:
    url: jdbc:postgresql://localhost:5432/cricketdb
    username: cricket
    password: cricket

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

cricket:
  import-on-startup: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
